import Head from "next/head";
import Link from "next/link";
import Footer from "../components/marketing/footer";
import Hero from "../components/marketing/hero.";
import Navbar from "../components/marketing/navbar";
import Pricing from "../components/marketing/pricing";
import Team from "../components/marketing/team";
import team from "../components/marketing/team";

export default function Home() {
  return (
    <div>
      <Head>
        <title>eTournaments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="bg-gray-50">
        <Hero />

        <div className="mx-auto max-w-7xl px-4 pt-12 sm:px-6 lg:px-8 scroll-mt-20">
          <h2 className="text-2xl font-medium sm:text-3xl sm:leading-tight sm:tracking-tight ">
            Pricing plans for every kind of gamer
          </h2>
          <p className="mt-4 max-w-3xl text-slate-500">
            Choose an affordable plan that has the best features for your
            tournament needs.
          </p>
        </div>
        <Pricing />
        <Team />
      </main>
    </div>
  );
}
